version: '3'

services:
  database:
    build:
      context: ./
      dockerfile: ./Dockerfile2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    networks:
      tp1_admin_default:
        ipv4_address: 10.5.0.5
    ports:
      - "3306:3306"

  web:
    build:
      context: ./
      dockerfile: ./Dockerfile1
    ports:
      - "5000:5000"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    depends_on:
      - database
    networks:
      tp1_admin_default:
        ipv4_address: 10.5.0.6

networks:
  tp1_admin_default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
